import React from "react";
import "./About.css";
import about_img from "../../assets/Trend.png";
import about_img2 from "../../assets/Abouttt.png";
import about_img3 from "../../assets/codt.png";
import about_img4 from "../../assets/Strategy.png";
import about_img5 from "../../assets/Aboutt.png";
import about_img6 from "../../assets/Abouttttt.png";


import play_icon from "../../assets/play-icon.png";

const About = () => {
  return (
    <>
      <div className="about">
        <div className="about-left">
          <img src={about_img} alt="" className="about-img" />
          <img src={play_icon} alt="" className="play-icon" />
        </div>
        <div className="about-right">
          <h3>Engagement </h3>
          <h2>Detecting Fake Engagement</h2>
          <p>
            Bot Detection: Use AI to identify bot activity, such as automated
            likes, comments, and follows, which can inflate engagement metrics
            artificially. Fake Followers: Detect inactive or fake accounts among
            an influencer’s followers to provide a more accurate picture of
            their true reach. Comment Authenticity: Analyze the content and
            patterns of comments to identify spam or fake comments generated by
            bots or low-quality engagement farms.
          </p>
          <p>
            Audience Demographics: Analyze the demographics of an influencer's
            followers to ensure alignment with the brand’s target audience.
            Engagement Quality: Evaluate the quality of engagement on an
            influencer’s posts, distinguishing between genuine interactions and
            superficial metrics.
          </p>
        </div>
      </div>
      <div className="about">
        <div className="about-right">
          <h3>REPORTS</h3>
          <h2>Comprehensive Reports</h2>
          <p>
            Influencer Scorecard: Provide a detailed report on each influencer,
            including metrics on engagement quality, audience authenticity, and
            potential reach. Red Flags: Highlight any red flags such as high
            percentages of bot followers, sudden spikes in follower count, or
            abnormal engagement patterns. Enhancing Advertiser Security and ROI
          </p>
          <p>
            Pre-Campaign Audits: Perform thorough audits of influencers before
            brands commit to collaborations, ensuring the influencer's audience
            is genuine and engaged. Ongoing Monitoring: Continuously monitor
            influencers during campaigns to track engagement and audience
            changes, ensuring continued alignment with campaign goals.
          </p>
        </div>
        <div className="about-left">
          <img src={about_img2} alt="" className="about-img" />
          <img src={play_icon} alt="" className="play-icon" />
        </div>
      </div>
      <div className="about">
        <div className="about-left">
          <img src={about_img3} alt="" className="about-img" />
          <img src={play_icon} alt="" className="play-icon" />
        </div>
        <div className="about-right">
          <h3>ANALYSIS</h3>
          <h2>Cost-Effectiveness Analysis</h2>
          <p>
            ROI Calculations: Provide detailed ROI analysis based on genuine
            engagement metrics, helping brands understand the true value
            delivered by each influencer. Campaign Optimization: Offer
            recommendations for optimizing influencer selection and campaign
            strategies based on data insights. Implementation Plan
          </p>
          <p>
            Social Media Integration: Integrate with major social media
            platforms to collect comprehensive data on influencers and their
            audiences. Third-Party Tools: Leverage third-party tools and APIs to
            enhance data collection and analysis capabilities.
          </p>
          <p>
            Fraud Detection Algorithms: Develop and refine algorithms
            specifically designed to detect fraudulent activities, including bot
            detection, fake followers, and spam comments. Engagement Analysis
            Models: Create models to assess the quality of interactions and
            identify genuine engagement.
          </p>
        </div>
      </div>
      <div className="about">
        <div className="about-right">
          <h3>MONITERING</h3>
          <h2>Competitor Ad Monitoring</h2>
          <p>
            Influencer Scorecard: Provide a detailed report on each influencer,
            including metrics on engagement quality, audience authenticity, and
            potential reach. Red Flags: Highlight any red flags such as high
            percentages of bot followers, sudden spikes in follower count, or
            abnormal engagement patterns. Enhancing Advertiser Security and ROI
          </p>
          <p>
            Pre-Campaign Audits: Perform thorough audits of influencers before
            brands commit to collaborations, ensuring the influencer's audience
            is genuine and engaged. Ongoing Monitoring: Continuously monitor
            influencers during campaigns to track engagement and audience
            changes, ensuring continued alignment with campaign goals.
          </p>
        </div>
        <div className="about-left">
          <img src={about_img4} alt="" className="about-img" />
          <img src={play_icon} alt="" className="play-icon" />
        </div>
      </div>
      <div className="about">
        <div className="about-left">
          <img src={about_img5} alt="" className="about-img" />
          <img src={play_icon} alt="" className="play-icon" />
        </div>
        <div className="about-right">
          <h3>ANALYSIS</h3>
          <h2>Influencer Analysis</h2>
          <p>
            ROI Calculations: Provide detailed ROI analysis based on genuine
            engagement metrics, helping brands understand the true value
            delivered by each influencer. Campaign Optimization: Offer
            recommendations for optimizing influencer selection and campaign
            strategies based on data insights. Implementation Plan
          </p>
          <p>
            Social Media Integration: Integrate with major social media
            platforms to collect comprehensive data on influencers and their
            audiences. Third-Party Tools: Leverage third-party tools and APIs to
            enhance data collection and analysis capabilities.
          </p>
          <p>
            Fraud Detection Algorithms: Develop and refine algorithms
            specifically designed to detect fraudulent activities, including bot
            detection, fake followers, and spam comments. Engagement Analysis
            Models: Create models to assess the quality of interactions and
            identify genuine engagement.
          </p>
        </div>
      </div>
      <div className="about">
        <div className="about-right">
          <h3>STRATEGY</h3>
          <h2>Strategy Insights</h2>
          <p>
            Influencer Scorecard: Provide a detailed report on each influencer,
            including metrics on engagement quality, audience authenticity, and
            potential reach. Red Flags: Highlight any red flags such as high
            percentages of bot followers, sudden spikes in follower count, or
            abnormal engagement patterns. Enhancing Advertiser Security and ROI
          </p>
          <p>
            Pre-Campaign Audits: Perform thorough audits of influencers before
            brands commit to collaborations, ensuring the influencer's audience
            is genuine and engaged. Ongoing Monitoring: Continuously monitor
            influencers during campaigns to track engagement and audience
            changes, ensuring continued alignment with campaign goals.
          </p>
        </div>
        <div className="about-left">
          <img src={about_img6} alt="" className="about-img" />
          <img src={play_icon} alt="" className="play-icon" />
        </div>
      </div>
    </>
  );
};

export default About;
